//
//  main.swift
//  Projet P3
//
//  Created by Anthony TUFFERY on 22/11/2020.
//entrance()

import Foundation




/*
 
 RESTANT A FAIRE :
 -VOIR INSTRUCTION GAME.SWIFT
 -TITRER TOUT LES FICHIERS CORRECTEMENT
 -NETTOYER LE CODE
 
 CREER LE COFFRE :
        -CREER LE COFFRE QUI CHOISIS ALEATOIREMENT LES ELEMENTS
        -CREER LA X-BLADE
        -CREER POTION QUI SOIGNE
        -CREER POTION QUI NIQUE
 
 INCORPORER LE COFFRE AU GAME() AFIN QU'IL SOIT UTILISER DE FACON ALEATOIRE DANS LE JEU
 SI ARME TROUVEE -> L'UTLISER OU LA LAISSER DANS LE COFFRE
                 -> SI UTILISÉE, REMPLACE L'ATTAQUE DE L'ARME PRINCIPAL PAR LA X-BLADE
 UNE FOIS UTILISE, SE BRISE. CREER UN PRINT QUI ANNONCE QUE L'ARME EST BRISÉ
 
 -CRÉATION D'UNE FONCTION QUI PERMET D'AFFICHER UN PRINT PRESONNALISÉ EN FONCTION DE LA SANTE DU PERSONNAGE ET DU PERSONNAGE EN LUI MEME (PHRASE PERSONNALISÉ POUR SORA ET XEHANORT STYLE IL PARLE EN DISANT "CEST PAS FINI, JE M'AVOUE PAS VAINCU ETC..) ETC..)
 
 */

intro()
game()
